from __future__ import annotations

import uuid

from src.ai_orbit.models import Entity, RawEntityRecord, Relationship, SourceRef


def stable_relationship_id(source_id: str, relationship_type: str, target_id: str, method: str) -> str:
    return str(uuid.uuid5(uuid.NAMESPACE_URL, f"ai-orbit:relationship:{source_id}:{relationship_type}:{target_id}:{method}"))


def map_relationships(
    raw_records: list[RawEntityRecord],
    entities: list[Entity],
    source_key_to_id: dict[str, str],
    task_edge_specs: dict[str, list[dict[str, str]]],
) -> list[Relationship]:
    relationships: dict[str, Relationship] = {}
    entity_by_id = {entity.id: entity for entity in entities}

    for record in raw_records:
        this_id = source_key_to_id.get(record.source_key)
        if not this_id:
            continue
        for pending in record.pending_relationships:
            other_id = source_key_to_id.get(pending.get("other_source_key", ""))
            if not other_id:
                continue
            if pending.get("direction") == "target_is_self":
                source_id, target_id = other_id, this_id
            else:
                source_id, target_id = this_id, other_id
            _add_relationship(
                relationships,
                source_id=source_id,
                target_id=target_id,
                relationship_type=pending["relationship_type"],
                method=pending.get("method", "source_pending_relationship"),
                evidence=pending.get("evidence", {}),
                source=SourceRef(name=record.source_name, url=record.source_url),
            )

    # Tool/repository/MCP -> solves -> Task edges generated by deterministic classification.
    for source_id, specs in task_edge_specs.items():
        source_entity = entity_by_id.get(source_id)
        if not source_entity:
            continue
        for spec in specs:
            target_id = source_key_to_id.get(spec["task_source_key"])
            if not target_id:
                continue
            _add_relationship(
                relationships,
                source_id=source_id,
                target_id=target_id,
                relationship_type="solves",
                method=f"task_mapping:{spec['method']}",
                evidence={
                    "observed_value": spec["observed_value"],
                    "source_url": spec["source_url"],
                    "reason": "controlled task mapping from observed source metadata",
                },
                source=source_entity.source,
            )

    return sorted(relationships.values(), key=lambda rel: rel.id)


def _add_relationship(
    relationships: dict[str, Relationship],
    *,
    source_id: str,
    target_id: str,
    relationship_type: str,
    method: str,
    evidence: dict[str, object],
    source: SourceRef,
) -> None:
    rel_id = stable_relationship_id(source_id, relationship_type, target_id, method)
    relationships[rel_id] = Relationship(
        id=rel_id,
        source_entity_id=source_id,
        target_entity_id=target_id,
        relationship_type=relationship_type,
        evidence=evidence,
        source=source,
        confidence=1.0,
        method=method,
    )
